### Importing Dataset

In [2]:
import pandas as pd
df = pd.read_csv('D:\\Vidhi\\DM Project\\WhatsappChatAnalyzer\\dataset\\twitter emotions.csv')

In [4]:
df.head()

      id                                               text emotion intensity
0  10857  @ZubairSabirPTI  pls dont insult the word 'Molna'   anger     0.479
1  10858  @ArcticFantasy I would have almost took offens...   anger     0.458
2  10859  @IllinoisLoyalty that Rutgers game was an abom...   anger     0.562
3  10860  @CozanGaming that's what lisa asked before she...   anger       0.5
4  10861  Sometimes I get mad over something so minuscul...   anger     0.708

### PREPROCESSING

In [5]:
df['text'].isnull().sum()

np.int64(0)

In [ ]:
df['emotion'].value_counts()   # somewhat balance dataset

emotion
fear       3357
anger      2545
joy        2409
sadness    2280
Name: count, dtype: int64

In [8]:
print(df['text'].sample(15).values)

<ArrowStringArray>
[                                                  'in my dream....They were trying to steal my kidney!!!  #blackmarket #whydidiwatchthat',
                                                                   'The outrage over Kessel's tweet by butthurt USA players is hilarious.',
                                                                                                   '@Hayles_101 The three R's depress me.',
                       '@CallofDuty how do u guys determine teams? Cause I'm 80% on shitty teams when I play and I'm fuckin over it #cod ',
        'Some #people already talks about #Halloween \nYou'll get some #dark #music to go with it\n#gothic #bloody #HalloweenHorrorNights',
                  'at least 5 ppl have left my stores in a huff in the past year but ive never had anyone call guest service on me yet so',
                                'Texans and Astros both shut out tonight. Houston, we're back to normal. #texans #Astros #sadness #losers',
 '@CTV_PowerPlay @lraitt Horrid disease! My maternal grandmother and each of her sisters suffered from this affliction. It's hard on all.',
                                             '@AriZernial @NesquikMills don't let him discourage you Z! That's one of the best ideas yet!',
        'Ugh I want to punch a wall every time I have to use @windows 10. Literally the worst product ever made #windows10 #awful #killme',
                                          'I turn 25 in two weeks. I am so happy. 24 was my darkest year yet. I am elated that I survived',
                                                                                                       'my life in one word is depressing',
                                                  'In 2016, Black people are STILL fighting to be recognized as human beings. #cantsleep ',
                                                          '.@POTUS Obama describes his temperament as 'steady &amp; on the buoyant side.'',
                                                                           'Or when they hmu on snap, and I'm like.. which one are you. 💀']
Length: 15, dtype: str

In [ ]:
import re
from nltk.stem import PorterStemmer
stemmer = PorterStemmer()

def preprocess_text(text):
    text = str(text).lower()
    text = re.sub(r"http\S+|www\S+", "", text)      # remove urls
    text = re.sub(r"@\w+", "", text)                # remove mentions like @ArcticFantasy
    text = re.sub(r"[^a-zA-Z\s]", " ", text)        # remove symbols
    text = re.sub(r"\s+", " ", text).strip()        # remove extra whitespace
    text = re.sub(r"\b\w\b", "", text)              # remove single characters
    text = re.sub(r"\d+", "", text)                 # remove numbers
    text = text.encode('ascii', 'ignore').decode('ascii') #removing emohis                                               #remove emojis

    #Stemming
    text = ' '.join(stemmer.stem(word) for word in text.split())

    return text

In [9]:
preprocess_text('This is a sample text! Visit http://example.com for more info. 😊 #NLP @user123')

'thi is sampl text visit for more info nlp'

In [10]:
df['text'] = df['text'].apply(preprocess_text)

In [11]:
df.head()

      id                                               text emotion intensity
0  10857                      pl dont insult the word molna   anger     0.479
1  10858  would have almost took offens to thi if actual...   anger     0.458
2  10859  that rutger game wa an abomin an affront to go...   anger     0.562
3  10860  that what lisa ask befor she start rage at me ...   anger       0.5
4  10861  sometim get mad over someth so minuscul tri to...   anger     0.708

In [ ]:
# Label encoding for emotion labels
from sklearn.preprocessing import LabelEncoder
label_encoder = LabelEncoder()
df['emotion'] = label_encoder.fit_transform(df['emotion'])

In [23]:
df['emotion'].value_counts()

emotion
1    3357
0    2545
2    2409
3    2280
Name: count, dtype: int64

In [24]:
import nltk
from sklearn.feature_extraction.text import TfidfVectorizer
nltk.download('stopwords')

vectorizer = TfidfVectorizer(stop_words='english',max_features=50000,
    ngram_range=(1,2),
    min_df=2,
    max_df=0.95
)
X_tfidf = vectorizer.fit_transform(df['text'])

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\DELL\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

In [25]:
# test train split
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_tfidf, df['emotion'], test_size=0.2, random_state=42, stratify=df['emotion'])

## MODEL

### Logistic Regression

In [17]:
from sklearn.linear_model import LogisticRegression
lr_model = LogisticRegression(max_iter=1000)
lr_model.fit(X_train, y_train)
y_pred = lr_model.predict(X_test)
from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

       anger       0.94      0.93      0.93       509
        fear       0.91      0.95      0.93       672
         joy       0.97      0.96      0.96       482
     sadness       0.89      0.86      0.87       456

    accuracy                           0.93      2119
   macro avg       0.93      0.92      0.93      2119
weighted avg       0.93      0.93      0.93      2119

In [18]:

from sklearn.metrics import confusion_matrix
confusion_matrix(y_test, y_pred)

array([[472,  14,   5,  18],
       [  5, 639,   2,  26],
       [  5,  12, 461,   4],
       [ 20,  37,   8, 391]])

### 2. SVM

In [19]:
from sklearn.svm import LinearSVC
svm_model = LinearSVC()
svm_model.fit(X_train, y_train)
y_pred_svm = svm_model.predict(X_test)
print(classification_report(y_test, y_pred_svm))

              precision    recall  f1-score   support

       anger       0.95      0.95      0.95       509
        fear       0.94      0.95      0.94       672
         joy       0.98      0.97      0.98       482
     sadness       0.89      0.88      0.88       456

    accuracy                           0.94      2119
   macro avg       0.94      0.94      0.94      2119
weighted avg       0.94      0.94      0.94      2119

### 3. XGBOOST

In [26]:
from xgboost import XGBClassifier

xgmodel = XGBClassifier(
    n_estimators=300,
    learning_rate=0.05,
    max_depth=5,
    min_child_weight=3,
    subsample=0.8,
    colsample_bytree=0.8,
    gamma=0.1,
    objective='binary:logistic',
    eval_metric='logloss'
)

xgmodel.fit(X_train, y_train)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=0.8, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric='logloss',
              feature_types=None, feature_weights=None, gamma=0.1,
              grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=0.05, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=5, max_leaves=None,
              min_child_weight=3, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=300, n_jobs=None,
              num_parallel_tree=None, ...)

In [28]:
print(classification_report(y_test, xgmodel.predict(X_test)))

              precision    recall  f1-score   support

           0       0.97      0.78      0.86       509
           1       0.74      0.94      0.83       672
           2       0.95      0.84      0.89       482
           3       0.88      0.82      0.84       456

    accuracy                           0.85      2119
   macro avg       0.88      0.85      0.86      2119
weighted avg       0.87      0.85      0.86      2119

In [ ]:
# Hyperparameter tuning of XGBoost using GridSearchCV
from sklearn.model_selection import GridSearchCV
param_grid = {
    'n_estimators': [100, 200],
    'learning_rate': [0.01, 0.1],
    'max_depth': [3, 6],
    'subsample': [0.8, 1.0],
    'colsample_bytree': [0.8, 1.0]
}
grid_search = GridSearchCV(estimator=XGBClassifier(objective='binary:logistic', eval_metric='logloss'), param_grid=param_grid, cv=3, n_jobs=-1, verbose=2)
grid_search.fit(X_train, y_train)
print("Best parameters found: ", grid_search.best_params_)
best_xgmodel = grid_search.best_estimator_

### CHAMPION MODEL - INTO PRODUCTION

In [31]:

import joblib
joblib.dump(svm_model, 'D:\\Vidhi\\DM Project\\WhatsappChatAnalyzer\\Trained_Models\\emotion_model.pkl')

['D:\\Vidhi\\DM Project\\WhatsappChatAnalyzer\\Trained_Models\\emotion_model.pkl']

In [32]:
joblib.dump(vectorizer, 'D:\\Vidhi\\DM Project\\WhatsappChatAnalyzer\\Trained_Models\\emotion_vectorizer.pkl')

['D:\\Vidhi\\DM Project\\WhatsappChatAnalyzer\\Trained_Models\\emotion_vectorizer.pkl']